printWidth = 90
semi = false
singleQuote = false
quoteProps = "preserve"
trailingComma = "none"
bracketSpacing = true
arrowParens = "avoid"
endOfLine = "auto"
pluginSearchDirs = ["."]

plugins = [
  "prettier-plugin-organize-imports",
  "prettier-plugin-jsdoc",
  "prettier-plugin-svelte",
]

# plugin-jsdoc
tsdoc = true
# Set shorter than 90 so if line wrapping is on comments don't go past it
jsdocPrintWidth = 75

# plugin-svelte
[[overrides]]
files = "**/*.svelte"
options = { parser = "svelte" }
