comment:
  layout: "reach, diff, flags, files"
  show_carryforward_flags: true

flags:
  clientmonorepo:
    carryforward: true
    paths:
      - client/

  # PHP backend and legacy frontend
  unittests:
    carryforward: true
    paths:
      - web/

  # ftml parser and renderer
  ftml:
    carryforward: true
    paths:
      - ftml/
