[package]
name = "deepwell"
description = "DEEPWELL - Wikijump API provider and database manager"
repository = "https://github.com/scpwiki/wikijump/tree/develop/deepwell"
readme = "README.md"
license = "AGPL-3.0-or-later"
keywords = ["wikijump", "api", "backend", "wiki"]
categories = ["asynchronous", "database", "web-programming::http-server"]
exclude = [".gitignore", ".editorconfig"]

version = "0.0.1"
authors = ["Ammon Smith <ammon.i.smith@gmail.com>"]
edition = "2021" # this is *not* the same as the current year
rust-version = "1.56.0"

[dependencies]
anyhow = "1"
async-std = { version = "1", features = ["attributes"] }
chrono = { version = "0.4", features = ["serde"] }
clap = "2"
dotenv = "0.15"
gettext = "0.4"
governor = "0.3"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.5", features = ["postgres", "chrono", "runtime-async-std-rustls"] }
tide = "0.16"
tide-sqlx = "0.6"

# Performance options

[profile.release]
lto = true
