name: wikijump

static_sites: []

services:
  - name: framerail
    dockerfile_path: install/aws/prod/docker/web/Dockerfile
    github:
      repo: scpwiki/wikijump
      branch: develop
      deploy_on_push: true
    autoscaling:
      min_instance_count: 1
      max_instance_count: 4
    instance_size_slug: basic-xxs
    health_check:
      initial_delay_seconds: 3

workers:
  - name: deepwell
    dockerfile_path: install/aws/prod/docker/api/Dockerfile
    github:
      repo: scpwiki/wikijump
      branch: develop
      deploy_on_push: true
    autoscaling:
      min_instance_count: 1
      max_instance_count: 4
    instance_size_slug: basic-xxs
    health_check:
      initial_delay_seconds: 1

databases:
  - engine: PG
    name: database
    version: '16'
