services:
  php-fpm:
    # Makes `host.docker.internal` resolve correctly to the host's IP on Linux
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - type: bind
        source: ../../../web/app
        target: /var/www/wikijump/web/app
        read_only: true
      - type: bind
        source: ../../../web/lib
        target: /var/www/wikijump/web/lib
        read_only: true
      - type: bind
        source: ../../../web/php
        target: /var/www/wikijump/web/php
        read_only: true
      - type: bind
        source: ../../../web/public/files--static
        target: /var/www/wikijump/web/public/files--static
        read_only: true
      - type: bind
        source: ../../../web/resources
        target: /var/www/wikijump/web/resources
        read_only: true
      - type: bind
        source: ../../../web/routes
        target: /var/www/wikijump/web/routes
        read_only: true
      - type: bind
        source: ../../../web/storage
        target: /var/www/wikijump/web/storage
        read_only: false
      - type: bind
        source: ../../../web/templates
        target: /var/www/wikijump/web/templates
        read_only: true
      - type: bind
        source: ../../../web/web
        target: /var/www/wikijump/web/web
        read_only: true
      - type: bind
        source: ../../../web/database
        target: /var/www/wikijump/web/database
        read_only: true

  nginx:
    labels:
      - traefik.enable=true
      - traefik.http.routers.php-fpm.tls=false
      - traefik.http.routers.php-fpm.rule=Method(`GET`,`POST`,`HEAD`,`PUT`,`PATCH`,`DELETE`)
    volumes:
      - type: bind
        source: ../../../web/web
        target: /var/www/wikijump/web/web
        read_only: true
      - type: bind
        source: ../../../web/public
        target: /var/www/wikijump/web/public
        read_only: true

  reverse-proxy:
    command:
      - --providers.docker
