services:
  nginx:
    labels:
      - traefik.enable=true
      - traefik.http.routers.php-fpm.tls=false
      - traefik.http.routers.php-fpm.rule=Method(`GET`,`POST`,`HEAD`,`PUT`,`PATCH`,`DELETE`)

  reverse-proxy:
    command:
      - --providers.docker
