version: '3.8'

services:
  database:
    build:
      context: ../../..
      dockerfile: install/local/dev/postgres/Dockerfile
    environment:
      - "POSTGRES_DB=wikijump"
      - "POSTGRES_USER=wikijump"
      - "POSTGRES_PASSWORD=wikijump"
      - "POSTGRES_HOST_AUTH_METHOD=md5"
      - "POSTGRES_INITDB_ARGS=--locale en_US.UTF-8"
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD", "wikijump-health-check"]
      interval: 10s
      timeout: 5s
      retries: 6

  files:
    build: files
    restart: always
    environment:
      - "MINIO_ROOT_USER=minio"
      - "MINIO_ROOT_PASSWORD=defaultpassword"
      - "MINIO_REGION_NAME=local"
      - "INITIAL_BUCKETS=deepwell-files"
      - "DATA_DIR=/data"  # You can add a volume for /data if you wish
    healthcheck:
      test: ["CMD", "curl", "-If", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "9000:9000"
      - "9001:9001"

  api:
    build:
      context: ../../..
      dockerfile: install/local/dev/api/Dockerfile
    ports:
      - "2747:2747"
    links:
      - files
    environment:
      - "DATABASE_URL=postgres://wikijump:wikijump@database/wikijump"
      - "LOCALIZATION_PATH=/opt/locales"
      - "RUN_MIGRATIONS=true"
      - "RUN_SEEDER=true"
      - "S3_BUCKET=deepwell-files"
      - "S3_REGION_NAME=local"
      - "S3_CUSTOM_ENDPOINT=http://files:9000"
      - "S3_ACCESS_KEY_ID=minio"
      - "S3_SECRET_ACCESS_KEY=defaultpassword"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-If", "http://localhost:2747/api/trusted/ping"]
      interval: 60s
      timeout: 2s
      retries: 3
    depends_on:
      database:
        condition: service_healthy
      files:
        condition: service_healthy
