version: '3.8'

services:
  cache:
    image: memcached:1.6-alpine
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "11211"]
      interval: 10s
      timeout: 5s
      retries: 3

  database:
    build:
      context: ../../..
      dockerfile: install/local/dev/postgres/Dockerfile
      args:
        FILES_DOMAIN: 'wjfiles.localhost'
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "wikijump"]
      interval: 10s
      timeout: 5s
      retries: 6

  nginx:
    build:
      context: ../../..
      dockerfile: install/local/dev/nginx/Dockerfile
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - php-fpm

  api:
    build:
      context: ../../..
      dockerfile: install/local/dev/api/Dockerfile
    ports:
      - "2747:2747"
    environment:
      - "DEEPWELL_DATABASE_URL=postgres://wikijump:wikijump@database/wikijump"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-i", "http://localhost:2747/api/v0/ping"]
      interval: 60s
      timeout: 2s
      retries: 3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      database:
        condition: service_healthy

  php-fpm:
    build:
      context: ../../..
      dockerfile: install/local/dev/php-fpm/Dockerfile
      args:
        MAIN_DOMAIN: 'wikijump.localhost'
        FILES_DOMAIN: 'wjfiles.localhost'
    restart: always
    depends_on:
      cache:
        condition: service_healthy
      database:
        condition: service_healthy
