version: '3.8'

services:
  api:
    volumes:
      # Rust sources
      - type: bind
        source: ../../../deepwell/src
        target: /src/deepwell/src
        read_only: true
      - type: bind
        source: ../../../deepwell/build.rs
        target: /src/deepwell/build.rs
        read_only: true
      - type: bind
        source: ../../../deepwell/Cargo.toml
        target: /src/deepwell/Cargo.toml
        read_only: true
      # Database files
      - type: bind
        source: ../../../deepwell/migrations
        target: /src/deepwell/migrations
        read_only: true
      - type: bind
        source: ../../../deepwell/seeder
        target: /src/deepwell/seeder
        read_only: true
      # Translation data
      - type: bind
        source: ../../../locales
        target: /opt/locales
        read_only: true
  web:
    volumes:
      # Typescript/Svelte files
      - type: bind
        source: ../../../framerail/src
        target: /app/src
        read_only: true
      - type: bind
        source: ../../../framerail/static
        target: /app/static
        read_only: true
      - type: bind
        source: ../../../framerail/package.json
        target: /app/package.json
        read_only: true
      - type: bind
        source: ../../../framerail/pnpm-lock.yaml
        target: /app/pnpm-lock.yaml
        read_only: true
      - type: bind
        source: ../../../framerail/svelte.config.js
        target: /app/svelte.config.js
        read_only: true
      - type: bind
        source: ../../../framerail/vite.config.ts
        target: /app/svelte.config.ts
        read_only: true
