services:
  php-fpm:
    volumes:
      # Laravel
      - type: bind
        source: ../../../web/app
        target: /var/www/wikijump/web/app
        read_only: true
      - type: bind
        source: ../../../web/database
        target: /var/www/wikijump/web/database
        read_only: true
      - type: bind
        source: ../../../web/routes
        target: /var/www/wikijump/web/routes
        read_only: true
      - type: bind
        source: ../../../web/storage
        target: /var/www/wikijump/web/storage
        read_only: false

      # Views
      - type: bind
        source: ../../../web/resources/views
        target: /var/www/wikijump/web/resources/views
        read_only: true

      # Legacy
      - type: bind
        source: ../../../web/lib
        target: /var/www/wikijump/web/lib
        read_only: true
      - type: bind
        source: ../../../web/php
        target: /var/www/wikijump/web/php
        read_only: true
      - type: bind
        source: ../../../web/templates
        target: /var/www/wikijump/web/templates
        read_only: true
      - type: bind
        source: ../../../web/web
        target: /var/www/wikijump/web/web
        read_only: true

  nginx:
    volumes:
      - type: bind
        source: ../../../web/web
        target: /var/www/wikijump/web/web
        read_only: true
      - type: bind
        source: ../../../web/public/files--static
        target: /var/www/wikijump/web/public/files--static
        read_only: true
