version: '3.8'
services:
  cache:
    image: memcached:1.6-alpine
  database:
    build:
      context: ./postgres
  nginx:
    build:
      context: ./nginx
  wikijump:
    build:
      context: ./wikijump
