version: '3.8'

services:
  cache:
    image: memcached:1.6-alpine
  database:
    build:
      context: ./postgres
      args:
        FILES_DOMAIN: 'wjfiles.test'
        POSTGRES_PASSWORD: 'wikijump-postgres'
  nginx:
    build:
      context: ./nginx
      args:
        MAIN_DOMAIN: 'wikijump.test'
        FILES_DOMAIN: 'wjfiles.test'
  php-fpm:
    build:
      context: ./php-fpm
