name: "[client monorepo] TypeScript"

on:
  push:
    paths:
      - "client/**"
      - "ftml/test/*"
      - ".github/workflows/client.yaml"

  pull_request:
    paths:
      - "client/**"
      - "ftml/test/*"
      - ".github/workflows/client.yaml"

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install
        run: cd client && npm ci --no-optional && npm run bootstrap

      - name: Test
        run: cd client && npm test

      - name: Lint
        run: cd client && npm run lint
