name: '[backend] Docker build API (dev)'

on:
  pull_request:
    paths:
      - 'deepwell/**'
      - 'install/dev/digitalocean/api/Dockerfile'
      - '.github/workflows/docker-build-api.dev.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -f install/dev/digitalocean/api/Dockerfile .
        env:
          DOCKER_BUILDKIT: 1
