name: '[deploy] Docker push Dokku'

on:
  push:
    branches:
      - develop
    paths:
      - 'deepwell/**'
      - 'framerail/**'
      - 'install/dev/dokku/Dockerfile'
      - '.github/workflows/docker-build-push-dokku.dev.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to Dokku
        uses: dokku/github-action@master
        with:
          ssh_private_key: ${{ secrets.DOKKU_DEPLOY_KEY }}
          git_remote_url: 'ssh://dokku@wikijump.dev:22/wikijump'
          git_push_flags: --force --verbose
