name: '[deploy] Docker push Deepwell'

on:
  push:
    branches:
      - develop
    paths:
      - 'deepwell/**'
      - 'install/aws/dev/docker/api/**'
      - '.github/workflows/docker-build-push-api.dev.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to Dokku
        uses: dokku/github-action@master
        with:
          ssh_private_key: ${{ secrets.DOKKU_DEPLOY_KEY }}
          git_remote_url: 'ssh://dokku@wikijump.dev:22/deepwell'
          git_push_flags: --force --verbose
