name: '[ftml] Rust'

on:
  push:
    paths:
      - 'ftml/Cargo.toml'
      - 'ftml/Cargo.lock'
      - 'ftml/ftml-http/**'
      - 'ftml/src/**'
      - 'ftml/test/*'
      - '.github/workflows/ftml.yaml'

jobs:
  library_build_and_test:
    name: Library
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('ftml/**/Cargo.toml') }}
      - run: cd ftml && cargo build --all-features --release
      - run: cd ftml && cargo test --all-features -- --nocapture --test-threads 1
      - run: cd ftml && cargo build --no-default-features --release
  wasm:
    name: WebASM
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('ftml/**/Cargo.toml') }}
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - run: cd ftml && wasm-pack build
      - run: cd ftml && wasm-pack build -- --features wasm-log
      - run: cd ftml && wasm-pack build -- --no-default-features
  clippy_lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('ftml/**/Cargo.toml') }}
      - run: cd ftml && cargo fmt --all -- --check
      - run: cd ftml && cargo clippy
