name: '[l10n] Localization'

on:
  push:
    paths:
      - 'locales/*.yaml'
      - 'locales/messages/**'
      - '.github/workflows/locales.yaml'

jobs:
  build:
    name: gettext File Generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Pip Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-locale-python-${{ hashFiles('locales/messages/requirements.txt') }}

      - name: Build
        run: |
          # Dependencies
          python -m pip install --upgrade pip
          pip install -r locales/messages/requirements.txt

          # Scripts
          cd locales
          python -m messages .
