version: '3.8'
services:
  cache:
    image: memcached:1.6
  database:
    build:
      context: ./postgres
    environment:
      - POSTGRES_PASSWORD=wikijump-postgres
  nginx:
    build:
      context: ./nginx
  wikijump:
    build:
      context: ./wikijump
